
[env:esp32dev]
platform = espressif32@6.6.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	knolleary/PubSubClient@^2.8
	adafruit/DHT sensor library@^1.4.7
	tzapu/WiFiManager@^2.0.16-rc.2
	bblanchon/ArduinoJson@^7.2.2
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SSD1306@^2.5.16
	cotestatnt/AsyncTelegram2@^2.3.4
build_flags = 

	-D USER_SETUP_LOADED
	-include User_Setup.h

upload_protocol = espota
upload_port = 192.168.68.106

upload_flags =
      --auth=1234